server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://wgwwgknifuiayn:8197ff75147442128996a7735194a71ac9bbbf195b719647588a24082b80b5db@ec2-184-73-198-174.compute-1.amazonaws.com:5432/d53bchr0ql1156
    username: wgwwgknifuiayn
    password: 8197ff75147442128996a7735194a71ac9bbbf195b719647588a24082b80b5db
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Bootcamp DIO - Santander
  version: 1.0.0
